### ISSUE TITLE
Incorrect logic + missing locations

### ISSUE THREAD

**Issue by BonkHolmes** [WolfBoi008/Five-Nights-at-Fuckboy-s-Complete-Collection#2]
Found a few missing locations during a first check
-Sex Toy Voucher
-Sex Toy
-Parts and Services Minigames
-Boxes on the Show Stage

Also a few logic fails
-Toy Bonnie, Toy Chica and Mangle having their first five levels be in logic from the start

**Comment by WolfBoi008** [comment]
The logic issue will be fixed as soon as possible.
I'll hold off on adding those two locations since I don't have a lot of time to add them just yet.
