### ISSUE TITLE
FNaFb2: Logic Oversight for {equipBeta()}, {equipGamma()}, {equipOmega()}, and {equipReal()}

### ISSUE THREAD

**Issue by WolfBoi008** [WolfBoi008/Five-Nights-at-Fuckboy-s-Complete-Collection#21]
The logic isn't right for these functions. I have to fix it as soon as possible.

**Comment by BonkHolmes** [comment]
As of November 13th, this is fixed.

**Comment by WolfBoi008** [comment]
This has been fixed as of Version 2.1.0.
